version: '3.1'
services:
  app:
    container_name: categoria-app
    image: categoria-app
    build: ./
    ports: 
      - '8181:8181'
    depends_on: 
      - mysql
  mysql: 
    image: mysql:latest
    environment: 
      - MYSQL_USER=root
      - MYSQL_DATABASE=app_categoria
      - MYSQL_PASSWORD=admin123
    ports: 
      - 3306:3306